# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

soft <- function(A, a, diag = 0) {
    .Call(`_EQUAL_soft`, A, a, diag)
}

equal1 <- function(X, lambda, err = 10^(-5), maxIter = 10^3L, rho = 1, diag = 0L) {
    .Call(`_EQUAL_equal1`, X, lambda, err, maxIter, rho, diag)
}

equal2 <- function(X, lambda, err = 10^(-5), maxIter = 10^3L, rho = 1, diag = 0L) {
    .Call(`_EQUAL_equal2`, X, lambda, err, maxIter, rho, diag)
}

